---
~/projects/work/razorpay:
    name: Nemo
    email: nemo@razorpay.com
~/projects/personal:
    name: Nemo
    email: me@captnemo.in
# AUR packages
~/projects/personal/aur:
    name: Nemo
    email: archlinux@captnemo.in
~/projects/personal/shauryaa:
    name: Abhishek
    email: mama@shauryaa.in
